export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';

export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_FAILED = 'FETCH_CARD_FAILED';

export const FETCH_TRANS_FAILED = 'FETCH_TRANS_FAILED';
export const FETCH_TRANS_SUCCESS = 'FETCH_TRANS_SUCCESS';

export const ACTIVE_CARD_CHANGE = 'ACTIVE_CARD_CHANGE';

export const MOBILE_PAY_SUCCESS = 'MOBILE_PAY_SUCCESS';
export const MOBILE_PAY_FAILED = 'MOBILE_PAY_FAILED';
export const MOBILE_PAY_REPEAT = 'MOBILE_PAY_REPEAT';
