export const USER_TOKEN_VERIFY_START = 'USER_TOKEN_VERIFY_START';
export const USER_TOKEN_VERIFY_COMPLETE = 'USER_TOKEN_VERIFY_COMPLETE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CARDS_FETCH_STARTED = 'CARDS_FETCH_STARTED';
export const CARDS_FETCH_SUCCESS = 'CARDS_FETCH_SUCCESS';
export const CARDS_FETCH_FAILED = 'CARDS_FETCH_FAILED';

export const CARD_ADD_STARTED = 'CARD_ADD_STARTED';
export const CARD_ADD_SUCCESS = 'CARD_ADD_SUCCESS';
export const CARD_ADD_FAILED = 'CARD_ADD_FAILED';

export const MR_ADD_STARTED = 'MR_ADD_STARTED';
export const MR_ADD_SUCCESS = 'MR_ADD_SUCCESS';
export const MR_ADD_FAILED = 'MR_ADD_FAILED';
export const MR_ADD_RESET_STATUS = 'MR_ADD_RESET_STATUS';

export const MR_FETCH_STARTED = 'MR_FETCH_STARTED';
export const MR_FETCH_SUCCESS = 'MR_FETCH_SUCCESS';
export const MR_FETCH_FAILED = 'MR_FETCH_FAILED';

export const CARD_DELETE_STARTED = 'CARD_DELETE_STARTED';
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS';
export const CARD_DELETE_FAILED = 'CARD_DELETE_FAILED';

export const CARD_FETCH_SUCCESS = 'CARD_FETCH_SUCCESS';
export const CARD_FETCH_FAILED = 'CARD_FETCH_FAILED';

export const TRANS_FETCH_STARTED = 'TRANS_FETCH_STARTED';
export const TRANS_FETCH_FAILED = 'TRANS_FETCH_FAILED';
export const TRANS_FETCH_SUCCESS = 'TRANS_FETCH_SUCCESS';

export const ACTIVE_CARD_CHANGED = 'ACTIVE_CARD_CHANGED';

export const MOBILE_PAY_SUCCESS = 'MOBILE_PAY_SUCCESS';
export const MOBILE_PAY_FAILED = 'MOBILE_PAY_FAILED';
export const MOBILE_PAY_REPEAT = 'MOBILE_PAY_REPEAT';

export const PREPAID_PAY_SUCCESS = 'PREPAID_PAY_SUCCESS';
export const PREPAID_PAY_FAILED = 'PREPAID_PAY_FAILED';
export const PREPAID_PAY_REPEAT = 'PREPAID_PAY_REPEAT';

export const WITHDRAW_PAY_SUCCESS = 'WITHDRAW_PAY_SUCCESS';
export const WITHDRAW_PAY_FAILED = 'WITHDRAW_PAY_FAILED';
export const WITHDRAW_PAY_REPEAT = 'WITHDRAW_PAY_REPEAT';

export const CURRENCY_RECEIVED = 'CURRENCY_RECEIVED';
export const CARD2USER_PAY_SUCCESS = 'CARD2USER_PAY_SUCCESS';
export const CARD2USER_PAY_FAILED = 'CARD2USER_PAY_FAILED';
export const CARD2USER_PAY_REPEAT = 'CARD2USER_PAY_REPEAT';
